// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/announcement"
	"github.com/Wei-Shaw/sub2api/ent/announcementcomment"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AnnouncementComment is the model entity for the AnnouncementComment schema.
type AnnouncementComment struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// AnnouncementID holds the value of the "announcement_id" field.
	AnnouncementID int64 `json:"announcement_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// ParentID holds the value of the "parent_id" field.
	ParentID *int64 `json:"parent_id,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AnnouncementCommentQuery when eager-loading is set.
	Edges        AnnouncementCommentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AnnouncementCommentEdges holds the relations/edges for other nodes in the graph.
type AnnouncementCommentEdges struct {
	// Announcement holds the value of the announcement edge.
	Announcement *Announcement `json:"announcement,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Parent holds the value of the parent edge.
	Parent *AnnouncementComment `json:"parent,omitempty"`
	// Replies holds the value of the replies edge.
	Replies []*AnnouncementComment `json:"replies,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// AnnouncementOrErr returns the Announcement value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AnnouncementCommentEdges) AnnouncementOrErr() (*Announcement, error) {
	if e.Announcement != nil {
		return e.Announcement, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: announcement.Label}
	}
	return nil, &NotLoadedError{edge: "announcement"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AnnouncementCommentEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AnnouncementCommentEdges) ParentOrErr() (*AnnouncementComment, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: announcementcomment.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// RepliesOrErr returns the Replies value or an error if the edge
// was not loaded in eager-loading.
func (e AnnouncementCommentEdges) RepliesOrErr() ([]*AnnouncementComment, error) {
	if e.loadedTypes[3] {
		return e.Replies, nil
	}
	return nil, &NotLoadedError{edge: "replies"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AnnouncementComment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case announcementcomment.FieldID, announcementcomment.FieldAnnouncementID, announcementcomment.FieldUserID, announcementcomment.FieldParentID:
			values[i] = new(sql.NullInt64)
		case announcementcomment.FieldContent:
			values[i] = new(sql.NullString)
		case announcementcomment.FieldCreatedAt, announcementcomment.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AnnouncementComment fields.
func (_m *AnnouncementComment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case announcementcomment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case announcementcomment.FieldAnnouncementID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field announcement_id", values[i])
			} else if value.Valid {
				_m.AnnouncementID = value.Int64
			}
		case announcementcomment.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case announcementcomment.FieldParentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = new(int64)
				*_m.ParentID = value.Int64
			}
		case announcementcomment.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case announcementcomment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case announcementcomment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AnnouncementComment.
// This includes values selected through modifiers, order, etc.
func (_m *AnnouncementComment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAnnouncement queries the "announcement" edge of the AnnouncementComment entity.
func (_m *AnnouncementComment) QueryAnnouncement() *AnnouncementQuery {
	return NewAnnouncementCommentClient(_m.config).QueryAnnouncement(_m)
}

// QueryUser queries the "user" edge of the AnnouncementComment entity.
func (_m *AnnouncementComment) QueryUser() *UserQuery {
	return NewAnnouncementCommentClient(_m.config).QueryUser(_m)
}

// QueryParent queries the "parent" edge of the AnnouncementComment entity.
func (_m *AnnouncementComment) QueryParent() *AnnouncementCommentQuery {
	return NewAnnouncementCommentClient(_m.config).QueryParent(_m)
}

// QueryReplies queries the "replies" edge of the AnnouncementComment entity.
func (_m *AnnouncementComment) QueryReplies() *AnnouncementCommentQuery {
	return NewAnnouncementCommentClient(_m.config).QueryReplies(_m)
}

// Update returns a builder for updating this AnnouncementComment.
// Note that you need to call AnnouncementComment.Unwrap() before calling this method if this AnnouncementComment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AnnouncementComment) Update() *AnnouncementCommentUpdateOne {
	return NewAnnouncementCommentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AnnouncementComment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AnnouncementComment) Unwrap() *AnnouncementComment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AnnouncementComment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AnnouncementComment) String() string {
	var builder strings.Builder
	builder.WriteString("AnnouncementComment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("announcement_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AnnouncementID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.ParentID; v != nil {
		builder.WriteString("parent_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AnnouncementComments is a parsable slice of AnnouncementComment.
type AnnouncementComments []*AnnouncementComment
