// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/announcement"
	"github.com/Wei-Shaw/sub2api/ent/announcementcomment"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AnnouncementCommentQuery is the builder for querying AnnouncementComment entities.
type AnnouncementCommentQuery struct {
	config
	ctx              *QueryContext
	order            []announcementcomment.OrderOption
	inters           []Interceptor
	predicates       []predicate.AnnouncementComment
	withAnnouncement *AnnouncementQuery
	withUser         *UserQuery
	withParent       *AnnouncementCommentQuery
	withReplies      *AnnouncementCommentQuery
	modifiers        []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AnnouncementCommentQuery builder.
func (_q *AnnouncementCommentQuery) Where(ps ...predicate.AnnouncementComment) *AnnouncementCommentQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AnnouncementCommentQuery) Limit(limit int) *AnnouncementCommentQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AnnouncementCommentQuery) Offset(offset int) *AnnouncementCommentQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AnnouncementCommentQuery) Unique(unique bool) *AnnouncementCommentQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AnnouncementCommentQuery) Order(o ...announcementcomment.OrderOption) *AnnouncementCommentQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAnnouncement chains the current query on the "announcement" edge.
func (_q *AnnouncementCommentQuery) QueryAnnouncement() *AnnouncementQuery {
	query := (&AnnouncementClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(announcementcomment.Table, announcementcomment.FieldID, selector),
			sqlgraph.To(announcement.Table, announcement.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, announcementcomment.AnnouncementTable, announcementcomment.AnnouncementColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (_q *AnnouncementCommentQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(announcementcomment.Table, announcementcomment.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, announcementcomment.UserTable, announcementcomment.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParent chains the current query on the "parent" edge.
func (_q *AnnouncementCommentQuery) QueryParent() *AnnouncementCommentQuery {
	query := (&AnnouncementCommentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(announcementcomment.Table, announcementcomment.FieldID, selector),
			sqlgraph.To(announcementcomment.Table, announcementcomment.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, announcementcomment.ParentTable, announcementcomment.ParentColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryReplies chains the current query on the "replies" edge.
func (_q *AnnouncementCommentQuery) QueryReplies() *AnnouncementCommentQuery {
	query := (&AnnouncementCommentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(announcementcomment.Table, announcementcomment.FieldID, selector),
			sqlgraph.To(announcementcomment.Table, announcementcomment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, announcementcomment.RepliesTable, announcementcomment.RepliesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AnnouncementComment entity from the query.
// Returns a *NotFoundError when no AnnouncementComment was found.
func (_q *AnnouncementCommentQuery) First(ctx context.Context) (*AnnouncementComment, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{announcementcomment.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AnnouncementCommentQuery) FirstX(ctx context.Context) *AnnouncementComment {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AnnouncementComment ID from the query.
// Returns a *NotFoundError when no AnnouncementComment ID was found.
func (_q *AnnouncementCommentQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{announcementcomment.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AnnouncementCommentQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AnnouncementComment entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AnnouncementComment entity is found.
// Returns a *NotFoundError when no AnnouncementComment entities are found.
func (_q *AnnouncementCommentQuery) Only(ctx context.Context) (*AnnouncementComment, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{announcementcomment.Label}
	default:
		return nil, &NotSingularError{announcementcomment.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AnnouncementCommentQuery) OnlyX(ctx context.Context) *AnnouncementComment {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AnnouncementComment ID in the query.
// Returns a *NotSingularError when more than one AnnouncementComment ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AnnouncementCommentQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{announcementcomment.Label}
	default:
		err = &NotSingularError{announcementcomment.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AnnouncementCommentQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AnnouncementComments.
func (_q *AnnouncementCommentQuery) All(ctx context.Context) ([]*AnnouncementComment, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AnnouncementComment, *AnnouncementCommentQuery]()
	return withInterceptors[[]*AnnouncementComment](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AnnouncementCommentQuery) AllX(ctx context.Context) []*AnnouncementComment {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AnnouncementComment IDs.
func (_q *AnnouncementCommentQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(announcementcomment.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AnnouncementCommentQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AnnouncementCommentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AnnouncementCommentQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AnnouncementCommentQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AnnouncementCommentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AnnouncementCommentQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AnnouncementCommentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AnnouncementCommentQuery) Clone() *AnnouncementCommentQuery {
	if _q == nil {
		return nil
	}
	return &AnnouncementCommentQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]announcementcomment.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.AnnouncementComment{}, _q.predicates...),
		withAnnouncement: _q.withAnnouncement.Clone(),
		withUser:         _q.withUser.Clone(),
		withParent:       _q.withParent.Clone(),
		withReplies:      _q.withReplies.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithAnnouncement tells the query-builder to eager-load the nodes that are connected to
// the "announcement" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AnnouncementCommentQuery) WithAnnouncement(opts ...func(*AnnouncementQuery)) *AnnouncementCommentQuery {
	query := (&AnnouncementClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAnnouncement = query
	return _q
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AnnouncementCommentQuery) WithUser(opts ...func(*UserQuery)) *AnnouncementCommentQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithParent tells the query-builder to eager-load the nodes that are connected to
// the "parent" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AnnouncementCommentQuery) WithParent(opts ...func(*AnnouncementCommentQuery)) *AnnouncementCommentQuery {
	query := (&AnnouncementCommentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withParent = query
	return _q
}

// WithReplies tells the query-builder to eager-load the nodes that are connected to
// the "replies" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AnnouncementCommentQuery) WithReplies(opts ...func(*AnnouncementCommentQuery)) *AnnouncementCommentQuery {
	query := (&AnnouncementCommentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withReplies = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AnnouncementID int64 `json:"announcement_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AnnouncementComment.Query().
//		GroupBy(announcementcomment.FieldAnnouncementID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AnnouncementCommentQuery) GroupBy(field string, fields ...string) *AnnouncementCommentGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AnnouncementCommentGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = announcementcomment.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AnnouncementID int64 `json:"announcement_id,omitempty"`
//	}
//
//	client.AnnouncementComment.Query().
//		Select(announcementcomment.FieldAnnouncementID).
//		Scan(ctx, &v)
func (_q *AnnouncementCommentQuery) Select(fields ...string) *AnnouncementCommentSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AnnouncementCommentSelect{AnnouncementCommentQuery: _q}
	sbuild.label = announcementcomment.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AnnouncementCommentSelect configured with the given aggregations.
func (_q *AnnouncementCommentQuery) Aggregate(fns ...AggregateFunc) *AnnouncementCommentSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AnnouncementCommentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !announcementcomment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AnnouncementCommentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AnnouncementComment, error) {
	var (
		nodes       = []*AnnouncementComment{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withAnnouncement != nil,
			_q.withUser != nil,
			_q.withParent != nil,
			_q.withReplies != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AnnouncementComment).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AnnouncementComment{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAnnouncement; query != nil {
		if err := _q.loadAnnouncement(ctx, query, nodes, nil,
			func(n *AnnouncementComment, e *Announcement) { n.Edges.Announcement = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *AnnouncementComment, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withParent; query != nil {
		if err := _q.loadParent(ctx, query, nodes, nil,
			func(n *AnnouncementComment, e *AnnouncementComment) { n.Edges.Parent = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withReplies; query != nil {
		if err := _q.loadReplies(ctx, query, nodes,
			func(n *AnnouncementComment) { n.Edges.Replies = []*AnnouncementComment{} },
			func(n *AnnouncementComment, e *AnnouncementComment) { n.Edges.Replies = append(n.Edges.Replies, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AnnouncementCommentQuery) loadAnnouncement(ctx context.Context, query *AnnouncementQuery, nodes []*AnnouncementComment, init func(*AnnouncementComment), assign func(*AnnouncementComment, *Announcement)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*AnnouncementComment)
	for i := range nodes {
		fk := nodes[i].AnnouncementID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(announcement.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "announcement_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AnnouncementCommentQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*AnnouncementComment, init func(*AnnouncementComment), assign func(*AnnouncementComment, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*AnnouncementComment)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AnnouncementCommentQuery) loadParent(ctx context.Context, query *AnnouncementCommentQuery, nodes []*AnnouncementComment, init func(*AnnouncementComment), assign func(*AnnouncementComment, *AnnouncementComment)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*AnnouncementComment)
	for i := range nodes {
		if nodes[i].ParentID == nil {
			continue
		}
		fk := *nodes[i].ParentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(announcementcomment.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "parent_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AnnouncementCommentQuery) loadReplies(ctx context.Context, query *AnnouncementCommentQuery, nodes []*AnnouncementComment, init func(*AnnouncementComment), assign func(*AnnouncementComment, *AnnouncementComment)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*AnnouncementComment)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(announcementcomment.FieldParentID)
	}
	query.Where(predicate.AnnouncementComment(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(announcementcomment.RepliesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ParentID
		if fk == nil {
			return fmt.Errorf(`foreign-key "parent_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "parent_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *AnnouncementCommentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AnnouncementCommentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(announcementcomment.Table, announcementcomment.Columns, sqlgraph.NewFieldSpec(announcementcomment.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, announcementcomment.FieldID)
		for i := range fields {
			if fields[i] != announcementcomment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withAnnouncement != nil {
			_spec.Node.AddColumnOnce(announcementcomment.FieldAnnouncementID)
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(announcementcomment.FieldUserID)
		}
		if _q.withParent != nil {
			_spec.Node.AddColumnOnce(announcementcomment.FieldParentID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AnnouncementCommentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(announcementcomment.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = announcementcomment.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *AnnouncementCommentQuery) ForUpdate(opts ...sql.LockOption) *AnnouncementCommentQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *AnnouncementCommentQuery) ForShare(opts ...sql.LockOption) *AnnouncementCommentQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// AnnouncementCommentGroupBy is the group-by builder for AnnouncementComment entities.
type AnnouncementCommentGroupBy struct {
	selector
	build *AnnouncementCommentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AnnouncementCommentGroupBy) Aggregate(fns ...AggregateFunc) *AnnouncementCommentGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AnnouncementCommentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AnnouncementCommentQuery, *AnnouncementCommentGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AnnouncementCommentGroupBy) sqlScan(ctx context.Context, root *AnnouncementCommentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AnnouncementCommentSelect is the builder for selecting fields of AnnouncementComment entities.
type AnnouncementCommentSelect struct {
	*AnnouncementCommentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AnnouncementCommentSelect) Aggregate(fns ...AggregateFunc) *AnnouncementCommentSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AnnouncementCommentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AnnouncementCommentQuery, *AnnouncementCommentSelect](ctx, _s.AnnouncementCommentQuery, _s, _s.inters, v)
}

func (_s *AnnouncementCommentSelect) sqlScan(ctx context.Context, root *AnnouncementCommentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
