// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/announcement"
	"github.com/Wei-Shaw/sub2api/ent/announcementcomment"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AnnouncementCommentCreate is the builder for creating a AnnouncementComment entity.
type AnnouncementCommentCreate struct {
	config
	mutation *AnnouncementCommentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAnnouncementID sets the "announcement_id" field.
func (_c *AnnouncementCommentCreate) SetAnnouncementID(v int64) *AnnouncementCommentCreate {
	_c.mutation.SetAnnouncementID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AnnouncementCommentCreate) SetUserID(v int64) *AnnouncementCommentCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *AnnouncementCommentCreate) SetParentID(v int64) *AnnouncementCommentCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *AnnouncementCommentCreate) SetNillableParentID(v *int64) *AnnouncementCommentCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *AnnouncementCommentCreate) SetContent(v string) *AnnouncementCommentCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AnnouncementCommentCreate) SetCreatedAt(v time.Time) *AnnouncementCommentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AnnouncementCommentCreate) SetNillableCreatedAt(v *time.Time) *AnnouncementCommentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AnnouncementCommentCreate) SetUpdatedAt(v time.Time) *AnnouncementCommentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AnnouncementCommentCreate) SetNillableUpdatedAt(v *time.Time) *AnnouncementCommentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAnnouncement sets the "announcement" edge to the Announcement entity.
func (_c *AnnouncementCommentCreate) SetAnnouncement(v *Announcement) *AnnouncementCommentCreate {
	return _c.SetAnnouncementID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *AnnouncementCommentCreate) SetUser(v *User) *AnnouncementCommentCreate {
	return _c.SetUserID(v.ID)
}

// SetParent sets the "parent" edge to the AnnouncementComment entity.
func (_c *AnnouncementCommentCreate) SetParent(v *AnnouncementComment) *AnnouncementCommentCreate {
	return _c.SetParentID(v.ID)
}

// AddReplyIDs adds the "replies" edge to the AnnouncementComment entity by IDs.
func (_c *AnnouncementCommentCreate) AddReplyIDs(ids ...int64) *AnnouncementCommentCreate {
	_c.mutation.AddReplyIDs(ids...)
	return _c
}

// AddReplies adds the "replies" edges to the AnnouncementComment entity.
func (_c *AnnouncementCommentCreate) AddReplies(v ...*AnnouncementComment) *AnnouncementCommentCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddReplyIDs(ids...)
}

// Mutation returns the AnnouncementCommentMutation object of the builder.
func (_c *AnnouncementCommentCreate) Mutation() *AnnouncementCommentMutation {
	return _c.mutation
}

// Save creates the AnnouncementComment in the database.
func (_c *AnnouncementCommentCreate) Save(ctx context.Context) (*AnnouncementComment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AnnouncementCommentCreate) SaveX(ctx context.Context) *AnnouncementComment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnnouncementCommentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnnouncementCommentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AnnouncementCommentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := announcementcomment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := announcementcomment.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AnnouncementCommentCreate) check() error {
	if _, ok := _c.mutation.AnnouncementID(); !ok {
		return &ValidationError{Name: "announcement_id", err: errors.New(`ent: missing required field "AnnouncementComment.announcement_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AnnouncementComment.user_id"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "AnnouncementComment.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := announcementcomment.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "AnnouncementComment.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AnnouncementComment.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AnnouncementComment.updated_at"`)}
	}
	if len(_c.mutation.AnnouncementIDs()) == 0 {
		return &ValidationError{Name: "announcement", err: errors.New(`ent: missing required edge "AnnouncementComment.announcement"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "AnnouncementComment.user"`)}
	}
	return nil
}

func (_c *AnnouncementCommentCreate) sqlSave(ctx context.Context) (*AnnouncementComment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AnnouncementCommentCreate) createSpec() (*AnnouncementComment, *sqlgraph.CreateSpec) {
	var (
		_node = &AnnouncementComment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(announcementcomment.Table, sqlgraph.NewFieldSpec(announcementcomment.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(announcementcomment.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(announcementcomment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(announcementcomment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.AnnouncementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementcomment.AnnouncementTable,
			Columns: []string{announcementcomment.AnnouncementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AnnouncementID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementcomment.UserTable,
			Columns: []string{announcementcomment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementcomment.ParentTable,
			Columns: []string{announcementcomment.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcementcomment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RepliesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   announcementcomment.RepliesTable,
			Columns: []string{announcementcomment.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcementcomment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AnnouncementComment.Create().
//		SetAnnouncementID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AnnouncementCommentUpsert) {
//			SetAnnouncementID(v+v).
//		}).
//		Exec(ctx)
func (_c *AnnouncementCommentCreate) OnConflict(opts ...sql.ConflictOption) *AnnouncementCommentUpsertOne {
	_c.conflict = opts
	return &AnnouncementCommentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AnnouncementComment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AnnouncementCommentCreate) OnConflictColumns(columns ...string) *AnnouncementCommentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AnnouncementCommentUpsertOne{
		create: _c,
	}
}

type (
	// AnnouncementCommentUpsertOne is the builder for "upsert"-ing
	//  one AnnouncementComment node.
	AnnouncementCommentUpsertOne struct {
		create *AnnouncementCommentCreate
	}

	// AnnouncementCommentUpsert is the "OnConflict" setter.
	AnnouncementCommentUpsert struct {
		*sql.UpdateSet
	}
)

// SetAnnouncementID sets the "announcement_id" field.
func (u *AnnouncementCommentUpsert) SetAnnouncementID(v int64) *AnnouncementCommentUpsert {
	u.Set(announcementcomment.FieldAnnouncementID, v)
	return u
}

// UpdateAnnouncementID sets the "announcement_id" field to the value that was provided on create.
func (u *AnnouncementCommentUpsert) UpdateAnnouncementID() *AnnouncementCommentUpsert {
	u.SetExcluded(announcementcomment.FieldAnnouncementID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AnnouncementCommentUpsert) SetUserID(v int64) *AnnouncementCommentUpsert {
	u.Set(announcementcomment.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AnnouncementCommentUpsert) UpdateUserID() *AnnouncementCommentUpsert {
	u.SetExcluded(announcementcomment.FieldUserID)
	return u
}

// SetParentID sets the "parent_id" field.
func (u *AnnouncementCommentUpsert) SetParentID(v int64) *AnnouncementCommentUpsert {
	u.Set(announcementcomment.FieldParentID, v)
	return u
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *AnnouncementCommentUpsert) UpdateParentID() *AnnouncementCommentUpsert {
	u.SetExcluded(announcementcomment.FieldParentID)
	return u
}

// ClearParentID clears the value of the "parent_id" field.
func (u *AnnouncementCommentUpsert) ClearParentID() *AnnouncementCommentUpsert {
	u.SetNull(announcementcomment.FieldParentID)
	return u
}

// SetContent sets the "content" field.
func (u *AnnouncementCommentUpsert) SetContent(v string) *AnnouncementCommentUpsert {
	u.Set(announcementcomment.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *AnnouncementCommentUpsert) UpdateContent() *AnnouncementCommentUpsert {
	u.SetExcluded(announcementcomment.FieldContent)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AnnouncementCommentUpsert) SetUpdatedAt(v time.Time) *AnnouncementCommentUpsert {
	u.Set(announcementcomment.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AnnouncementCommentUpsert) UpdateUpdatedAt() *AnnouncementCommentUpsert {
	u.SetExcluded(announcementcomment.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AnnouncementComment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AnnouncementCommentUpsertOne) UpdateNewValues() *AnnouncementCommentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(announcementcomment.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AnnouncementComment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AnnouncementCommentUpsertOne) Ignore() *AnnouncementCommentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AnnouncementCommentUpsertOne) DoNothing() *AnnouncementCommentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AnnouncementCommentCreate.OnConflict
// documentation for more info.
func (u *AnnouncementCommentUpsertOne) Update(set func(*AnnouncementCommentUpsert)) *AnnouncementCommentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AnnouncementCommentUpsert{UpdateSet: update})
	}))
	return u
}

// SetAnnouncementID sets the "announcement_id" field.
func (u *AnnouncementCommentUpsertOne) SetAnnouncementID(v int64) *AnnouncementCommentUpsertOne {
	return u.Update(func(s *AnnouncementCommentUpsert) {
		s.SetAnnouncementID(v)
	})
}

// UpdateAnnouncementID sets the "announcement_id" field to the value that was provided on create.
func (u *AnnouncementCommentUpsertOne) UpdateAnnouncementID() *AnnouncementCommentUpsertOne {
	return u.Update(func(s *AnnouncementCommentUpsert) {
		s.UpdateAnnouncementID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AnnouncementCommentUpsertOne) SetUserID(v int64) *AnnouncementCommentUpsertOne {
	return u.Update(func(s *AnnouncementCommentUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AnnouncementCommentUpsertOne) UpdateUserID() *AnnouncementCommentUpsertOne {
	return u.Update(func(s *AnnouncementCommentUpsert) {
		s.UpdateUserID()
	})
}

// SetParentID sets the "parent_id" field.
func (u *AnnouncementCommentUpsertOne) SetParentID(v int64) *AnnouncementCommentUpsertOne {
	return u.Update(func(s *AnnouncementCommentUpsert) {
		s.SetParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *AnnouncementCommentUpsertOne) UpdateParentID() *AnnouncementCommentUpsertOne {
	return u.Update(func(s *AnnouncementCommentUpsert) {
		s.UpdateParentID()
	})
}

// ClearParentID clears the value of the "parent_id" field.
func (u *AnnouncementCommentUpsertOne) ClearParentID() *AnnouncementCommentUpsertOne {
	return u.Update(func(s *AnnouncementCommentUpsert) {
		s.ClearParentID()
	})
}

// SetContent sets the "content" field.
func (u *AnnouncementCommentUpsertOne) SetContent(v string) *AnnouncementCommentUpsertOne {
	return u.Update(func(s *AnnouncementCommentUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *AnnouncementCommentUpsertOne) UpdateContent() *AnnouncementCommentUpsertOne {
	return u.Update(func(s *AnnouncementCommentUpsert) {
		s.UpdateContent()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AnnouncementCommentUpsertOne) SetUpdatedAt(v time.Time) *AnnouncementCommentUpsertOne {
	return u.Update(func(s *AnnouncementCommentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AnnouncementCommentUpsertOne) UpdateUpdatedAt() *AnnouncementCommentUpsertOne {
	return u.Update(func(s *AnnouncementCommentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AnnouncementCommentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AnnouncementCommentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AnnouncementCommentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AnnouncementCommentUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AnnouncementCommentUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AnnouncementCommentCreateBulk is the builder for creating many AnnouncementComment entities in bulk.
type AnnouncementCommentCreateBulk struct {
	config
	err      error
	builders []*AnnouncementCommentCreate
	conflict []sql.ConflictOption
}

// Save creates the AnnouncementComment entities in the database.
func (_c *AnnouncementCommentCreateBulk) Save(ctx context.Context) ([]*AnnouncementComment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AnnouncementComment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AnnouncementCommentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AnnouncementCommentCreateBulk) SaveX(ctx context.Context) []*AnnouncementComment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnnouncementCommentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnnouncementCommentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AnnouncementComment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AnnouncementCommentUpsert) {
//			SetAnnouncementID(v+v).
//		}).
//		Exec(ctx)
func (_c *AnnouncementCommentCreateBulk) OnConflict(opts ...sql.ConflictOption) *AnnouncementCommentUpsertBulk {
	_c.conflict = opts
	return &AnnouncementCommentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AnnouncementComment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AnnouncementCommentCreateBulk) OnConflictColumns(columns ...string) *AnnouncementCommentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AnnouncementCommentUpsertBulk{
		create: _c,
	}
}

// AnnouncementCommentUpsertBulk is the builder for "upsert"-ing
// a bulk of AnnouncementComment nodes.
type AnnouncementCommentUpsertBulk struct {
	create *AnnouncementCommentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AnnouncementComment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AnnouncementCommentUpsertBulk) UpdateNewValues() *AnnouncementCommentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(announcementcomment.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AnnouncementComment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AnnouncementCommentUpsertBulk) Ignore() *AnnouncementCommentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AnnouncementCommentUpsertBulk) DoNothing() *AnnouncementCommentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AnnouncementCommentCreateBulk.OnConflict
// documentation for more info.
func (u *AnnouncementCommentUpsertBulk) Update(set func(*AnnouncementCommentUpsert)) *AnnouncementCommentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AnnouncementCommentUpsert{UpdateSet: update})
	}))
	return u
}

// SetAnnouncementID sets the "announcement_id" field.
func (u *AnnouncementCommentUpsertBulk) SetAnnouncementID(v int64) *AnnouncementCommentUpsertBulk {
	return u.Update(func(s *AnnouncementCommentUpsert) {
		s.SetAnnouncementID(v)
	})
}

// UpdateAnnouncementID sets the "announcement_id" field to the value that was provided on create.
func (u *AnnouncementCommentUpsertBulk) UpdateAnnouncementID() *AnnouncementCommentUpsertBulk {
	return u.Update(func(s *AnnouncementCommentUpsert) {
		s.UpdateAnnouncementID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AnnouncementCommentUpsertBulk) SetUserID(v int64) *AnnouncementCommentUpsertBulk {
	return u.Update(func(s *AnnouncementCommentUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AnnouncementCommentUpsertBulk) UpdateUserID() *AnnouncementCommentUpsertBulk {
	return u.Update(func(s *AnnouncementCommentUpsert) {
		s.UpdateUserID()
	})
}

// SetParentID sets the "parent_id" field.
func (u *AnnouncementCommentUpsertBulk) SetParentID(v int64) *AnnouncementCommentUpsertBulk {
	return u.Update(func(s *AnnouncementCommentUpsert) {
		s.SetParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *AnnouncementCommentUpsertBulk) UpdateParentID() *AnnouncementCommentUpsertBulk {
	return u.Update(func(s *AnnouncementCommentUpsert) {
		s.UpdateParentID()
	})
}

// ClearParentID clears the value of the "parent_id" field.
func (u *AnnouncementCommentUpsertBulk) ClearParentID() *AnnouncementCommentUpsertBulk {
	return u.Update(func(s *AnnouncementCommentUpsert) {
		s.ClearParentID()
	})
}

// SetContent sets the "content" field.
func (u *AnnouncementCommentUpsertBulk) SetContent(v string) *AnnouncementCommentUpsertBulk {
	return u.Update(func(s *AnnouncementCommentUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *AnnouncementCommentUpsertBulk) UpdateContent() *AnnouncementCommentUpsertBulk {
	return u.Update(func(s *AnnouncementCommentUpsert) {
		s.UpdateContent()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AnnouncementCommentUpsertBulk) SetUpdatedAt(v time.Time) *AnnouncementCommentUpsertBulk {
	return u.Update(func(s *AnnouncementCommentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AnnouncementCommentUpsertBulk) UpdateUpdatedAt() *AnnouncementCommentUpsertBulk {
	return u.Update(func(s *AnnouncementCommentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AnnouncementCommentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AnnouncementCommentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AnnouncementCommentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AnnouncementCommentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
