// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/announcement"
	"github.com/Wei-Shaw/sub2api/ent/announcementcomment"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AnnouncementCommentUpdate is the builder for updating AnnouncementComment entities.
type AnnouncementCommentUpdate struct {
	config
	hooks    []Hook
	mutation *AnnouncementCommentMutation
}

// Where appends a list predicates to the AnnouncementCommentUpdate builder.
func (_u *AnnouncementCommentUpdate) Where(ps ...predicate.AnnouncementComment) *AnnouncementCommentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAnnouncementID sets the "announcement_id" field.
func (_u *AnnouncementCommentUpdate) SetAnnouncementID(v int64) *AnnouncementCommentUpdate {
	_u.mutation.SetAnnouncementID(v)
	return _u
}

// SetNillableAnnouncementID sets the "announcement_id" field if the given value is not nil.
func (_u *AnnouncementCommentUpdate) SetNillableAnnouncementID(v *int64) *AnnouncementCommentUpdate {
	if v != nil {
		_u.SetAnnouncementID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AnnouncementCommentUpdate) SetUserID(v int64) *AnnouncementCommentUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AnnouncementCommentUpdate) SetNillableUserID(v *int64) *AnnouncementCommentUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *AnnouncementCommentUpdate) SetParentID(v int64) *AnnouncementCommentUpdate {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *AnnouncementCommentUpdate) SetNillableParentID(v *int64) *AnnouncementCommentUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *AnnouncementCommentUpdate) ClearParentID() *AnnouncementCommentUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetContent sets the "content" field.
func (_u *AnnouncementCommentUpdate) SetContent(v string) *AnnouncementCommentUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *AnnouncementCommentUpdate) SetNillableContent(v *string) *AnnouncementCommentUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AnnouncementCommentUpdate) SetUpdatedAt(v time.Time) *AnnouncementCommentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAnnouncement sets the "announcement" edge to the Announcement entity.
func (_u *AnnouncementCommentUpdate) SetAnnouncement(v *Announcement) *AnnouncementCommentUpdate {
	return _u.SetAnnouncementID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *AnnouncementCommentUpdate) SetUser(v *User) *AnnouncementCommentUpdate {
	return _u.SetUserID(v.ID)
}

// SetParent sets the "parent" edge to the AnnouncementComment entity.
func (_u *AnnouncementCommentUpdate) SetParent(v *AnnouncementComment) *AnnouncementCommentUpdate {
	return _u.SetParentID(v.ID)
}

// AddReplyIDs adds the "replies" edge to the AnnouncementComment entity by IDs.
func (_u *AnnouncementCommentUpdate) AddReplyIDs(ids ...int64) *AnnouncementCommentUpdate {
	_u.mutation.AddReplyIDs(ids...)
	return _u
}

// AddReplies adds the "replies" edges to the AnnouncementComment entity.
func (_u *AnnouncementCommentUpdate) AddReplies(v ...*AnnouncementComment) *AnnouncementCommentUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReplyIDs(ids...)
}

// Mutation returns the AnnouncementCommentMutation object of the builder.
func (_u *AnnouncementCommentUpdate) Mutation() *AnnouncementCommentMutation {
	return _u.mutation
}

// ClearAnnouncement clears the "announcement" edge to the Announcement entity.
func (_u *AnnouncementCommentUpdate) ClearAnnouncement() *AnnouncementCommentUpdate {
	_u.mutation.ClearAnnouncement()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AnnouncementCommentUpdate) ClearUser() *AnnouncementCommentUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearParent clears the "parent" edge to the AnnouncementComment entity.
func (_u *AnnouncementCommentUpdate) ClearParent() *AnnouncementCommentUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearReplies clears all "replies" edges to the AnnouncementComment entity.
func (_u *AnnouncementCommentUpdate) ClearReplies() *AnnouncementCommentUpdate {
	_u.mutation.ClearReplies()
	return _u
}

// RemoveReplyIDs removes the "replies" edge to AnnouncementComment entities by IDs.
func (_u *AnnouncementCommentUpdate) RemoveReplyIDs(ids ...int64) *AnnouncementCommentUpdate {
	_u.mutation.RemoveReplyIDs(ids...)
	return _u
}

// RemoveReplies removes "replies" edges to AnnouncementComment entities.
func (_u *AnnouncementCommentUpdate) RemoveReplies(v ...*AnnouncementComment) *AnnouncementCommentUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReplyIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AnnouncementCommentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnnouncementCommentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AnnouncementCommentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnnouncementCommentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AnnouncementCommentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := announcementcomment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnnouncementCommentUpdate) check() error {
	if v, ok := _u.mutation.Content(); ok {
		if err := announcementcomment.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "AnnouncementComment.content": %w`, err)}
		}
	}
	if _u.mutation.AnnouncementCleared() && len(_u.mutation.AnnouncementIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AnnouncementComment.announcement"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AnnouncementComment.user"`)
	}
	return nil
}

func (_u *AnnouncementCommentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(announcementcomment.Table, announcementcomment.Columns, sqlgraph.NewFieldSpec(announcementcomment.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(announcementcomment.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(announcementcomment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AnnouncementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementcomment.AnnouncementTable,
			Columns: []string{announcementcomment.AnnouncementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnnouncementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementcomment.AnnouncementTable,
			Columns: []string{announcementcomment.AnnouncementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementcomment.UserTable,
			Columns: []string{announcementcomment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementcomment.UserTable,
			Columns: []string{announcementcomment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementcomment.ParentTable,
			Columns: []string{announcementcomment.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcementcomment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementcomment.ParentTable,
			Columns: []string{announcementcomment.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcementcomment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RepliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   announcementcomment.RepliesTable,
			Columns: []string{announcementcomment.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcementcomment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRepliesIDs(); len(nodes) > 0 && !_u.mutation.RepliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   announcementcomment.RepliesTable,
			Columns: []string{announcementcomment.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcementcomment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RepliesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   announcementcomment.RepliesTable,
			Columns: []string{announcementcomment.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcementcomment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{announcementcomment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AnnouncementCommentUpdateOne is the builder for updating a single AnnouncementComment entity.
type AnnouncementCommentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AnnouncementCommentMutation
}

// SetAnnouncementID sets the "announcement_id" field.
func (_u *AnnouncementCommentUpdateOne) SetAnnouncementID(v int64) *AnnouncementCommentUpdateOne {
	_u.mutation.SetAnnouncementID(v)
	return _u
}

// SetNillableAnnouncementID sets the "announcement_id" field if the given value is not nil.
func (_u *AnnouncementCommentUpdateOne) SetNillableAnnouncementID(v *int64) *AnnouncementCommentUpdateOne {
	if v != nil {
		_u.SetAnnouncementID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AnnouncementCommentUpdateOne) SetUserID(v int64) *AnnouncementCommentUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AnnouncementCommentUpdateOne) SetNillableUserID(v *int64) *AnnouncementCommentUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *AnnouncementCommentUpdateOne) SetParentID(v int64) *AnnouncementCommentUpdateOne {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *AnnouncementCommentUpdateOne) SetNillableParentID(v *int64) *AnnouncementCommentUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *AnnouncementCommentUpdateOne) ClearParentID() *AnnouncementCommentUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetContent sets the "content" field.
func (_u *AnnouncementCommentUpdateOne) SetContent(v string) *AnnouncementCommentUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *AnnouncementCommentUpdateOne) SetNillableContent(v *string) *AnnouncementCommentUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AnnouncementCommentUpdateOne) SetUpdatedAt(v time.Time) *AnnouncementCommentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAnnouncement sets the "announcement" edge to the Announcement entity.
func (_u *AnnouncementCommentUpdateOne) SetAnnouncement(v *Announcement) *AnnouncementCommentUpdateOne {
	return _u.SetAnnouncementID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *AnnouncementCommentUpdateOne) SetUser(v *User) *AnnouncementCommentUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetParent sets the "parent" edge to the AnnouncementComment entity.
func (_u *AnnouncementCommentUpdateOne) SetParent(v *AnnouncementComment) *AnnouncementCommentUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddReplyIDs adds the "replies" edge to the AnnouncementComment entity by IDs.
func (_u *AnnouncementCommentUpdateOne) AddReplyIDs(ids ...int64) *AnnouncementCommentUpdateOne {
	_u.mutation.AddReplyIDs(ids...)
	return _u
}

// AddReplies adds the "replies" edges to the AnnouncementComment entity.
func (_u *AnnouncementCommentUpdateOne) AddReplies(v ...*AnnouncementComment) *AnnouncementCommentUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReplyIDs(ids...)
}

// Mutation returns the AnnouncementCommentMutation object of the builder.
func (_u *AnnouncementCommentUpdateOne) Mutation() *AnnouncementCommentMutation {
	return _u.mutation
}

// ClearAnnouncement clears the "announcement" edge to the Announcement entity.
func (_u *AnnouncementCommentUpdateOne) ClearAnnouncement() *AnnouncementCommentUpdateOne {
	_u.mutation.ClearAnnouncement()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AnnouncementCommentUpdateOne) ClearUser() *AnnouncementCommentUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearParent clears the "parent" edge to the AnnouncementComment entity.
func (_u *AnnouncementCommentUpdateOne) ClearParent() *AnnouncementCommentUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearReplies clears all "replies" edges to the AnnouncementComment entity.
func (_u *AnnouncementCommentUpdateOne) ClearReplies() *AnnouncementCommentUpdateOne {
	_u.mutation.ClearReplies()
	return _u
}

// RemoveReplyIDs removes the "replies" edge to AnnouncementComment entities by IDs.
func (_u *AnnouncementCommentUpdateOne) RemoveReplyIDs(ids ...int64) *AnnouncementCommentUpdateOne {
	_u.mutation.RemoveReplyIDs(ids...)
	return _u
}

// RemoveReplies removes "replies" edges to AnnouncementComment entities.
func (_u *AnnouncementCommentUpdateOne) RemoveReplies(v ...*AnnouncementComment) *AnnouncementCommentUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReplyIDs(ids...)
}

// Where appends a list predicates to the AnnouncementCommentUpdate builder.
func (_u *AnnouncementCommentUpdateOne) Where(ps ...predicate.AnnouncementComment) *AnnouncementCommentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AnnouncementCommentUpdateOne) Select(field string, fields ...string) *AnnouncementCommentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AnnouncementComment entity.
func (_u *AnnouncementCommentUpdateOne) Save(ctx context.Context) (*AnnouncementComment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnnouncementCommentUpdateOne) SaveX(ctx context.Context) *AnnouncementComment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AnnouncementCommentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnnouncementCommentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AnnouncementCommentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := announcementcomment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnnouncementCommentUpdateOne) check() error {
	if v, ok := _u.mutation.Content(); ok {
		if err := announcementcomment.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "AnnouncementComment.content": %w`, err)}
		}
	}
	if _u.mutation.AnnouncementCleared() && len(_u.mutation.AnnouncementIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AnnouncementComment.announcement"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AnnouncementComment.user"`)
	}
	return nil
}

func (_u *AnnouncementCommentUpdateOne) sqlSave(ctx context.Context) (_node *AnnouncementComment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(announcementcomment.Table, announcementcomment.Columns, sqlgraph.NewFieldSpec(announcementcomment.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AnnouncementComment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, announcementcomment.FieldID)
		for _, f := range fields {
			if !announcementcomment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != announcementcomment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(announcementcomment.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(announcementcomment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AnnouncementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementcomment.AnnouncementTable,
			Columns: []string{announcementcomment.AnnouncementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnnouncementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementcomment.AnnouncementTable,
			Columns: []string{announcementcomment.AnnouncementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementcomment.UserTable,
			Columns: []string{announcementcomment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementcomment.UserTable,
			Columns: []string{announcementcomment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementcomment.ParentTable,
			Columns: []string{announcementcomment.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcementcomment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementcomment.ParentTable,
			Columns: []string{announcementcomment.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcementcomment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RepliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   announcementcomment.RepliesTable,
			Columns: []string{announcementcomment.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcementcomment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRepliesIDs(); len(nodes) > 0 && !_u.mutation.RepliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   announcementcomment.RepliesTable,
			Columns: []string{announcementcomment.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcementcomment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RepliesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   announcementcomment.RepliesTable,
			Columns: []string{announcementcomment.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcementcomment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AnnouncementComment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{announcementcomment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
