// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/ticket"
	"github.com/Wei-Shaw/sub2api/ent/ticketmessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// TicketUpdate is the builder for updating Ticket entities.
type TicketUpdate struct {
	config
	hooks    []Hook
	mutation *TicketMutation
}

// Where appends a list predicates to the TicketUpdate builder.
func (_u *TicketUpdate) Where(ps ...predicate.Ticket) *TicketUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TicketUpdate) SetUserID(v int64) *TicketUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableUserID(v *int64) *TicketUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *TicketUpdate) SetTitle(v string) *TicketUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableTitle(v *string) *TicketUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TicketUpdate) SetStatus(v string) *TicketUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableStatus(v *string) *TicketUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TicketUpdate) SetCreatedBy(v int64) *TicketUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableCreatedBy(v *int64) *TicketUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *TicketUpdate) AddCreatedBy(v int64) *TicketUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *TicketUpdate) ClearCreatedBy() *TicketUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetClosedBy sets the "closed_by" field.
func (_u *TicketUpdate) SetClosedBy(v int64) *TicketUpdate {
	_u.mutation.ResetClosedBy()
	_u.mutation.SetClosedBy(v)
	return _u
}

// SetNillableClosedBy sets the "closed_by" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableClosedBy(v *int64) *TicketUpdate {
	if v != nil {
		_u.SetClosedBy(*v)
	}
	return _u
}

// AddClosedBy adds value to the "closed_by" field.
func (_u *TicketUpdate) AddClosedBy(v int64) *TicketUpdate {
	_u.mutation.AddClosedBy(v)
	return _u
}

// ClearClosedBy clears the value of the "closed_by" field.
func (_u *TicketUpdate) ClearClosedBy() *TicketUpdate {
	_u.mutation.ClearClosedBy()
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *TicketUpdate) SetClosedAt(v time.Time) *TicketUpdate {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableClosedAt(v *time.Time) *TicketUpdate {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *TicketUpdate) ClearClosedAt() *TicketUpdate {
	_u.mutation.ClearClosedAt()
	return _u
}

// SetLastReplyAt sets the "last_reply_at" field.
func (_u *TicketUpdate) SetLastReplyAt(v time.Time) *TicketUpdate {
	_u.mutation.SetLastReplyAt(v)
	return _u
}

// SetNillableLastReplyAt sets the "last_reply_at" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableLastReplyAt(v *time.Time) *TicketUpdate {
	if v != nil {
		_u.SetLastReplyAt(*v)
	}
	return _u
}

// ClearLastReplyAt clears the value of the "last_reply_at" field.
func (_u *TicketUpdate) ClearLastReplyAt() *TicketUpdate {
	_u.mutation.ClearLastReplyAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TicketUpdate) SetUpdatedAt(v time.Time) *TicketUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *TicketUpdate) SetUser(v *User) *TicketUpdate {
	return _u.SetUserID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the TicketMessage entity by IDs.
func (_u *TicketUpdate) AddMessageIDs(ids ...int64) *TicketUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the TicketMessage entity.
func (_u *TicketUpdate) AddMessages(v ...*TicketMessage) *TicketUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the TicketMutation object of the builder.
func (_u *TicketUpdate) Mutation() *TicketMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TicketUpdate) ClearUser() *TicketUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearMessages clears all "messages" edges to the TicketMessage entity.
func (_u *TicketUpdate) ClearMessages() *TicketUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to TicketMessage entities by IDs.
func (_u *TicketUpdate) RemoveMessageIDs(ids ...int64) *TicketUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to TicketMessage entities.
func (_u *TicketUpdate) RemoveMessages(v ...*TicketMessage) *TicketUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TicketUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TicketUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TicketUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TicketUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TicketUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ticket.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TicketUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := ticket.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Ticket.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := ticket.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Ticket.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Ticket.user"`)
	}
	return nil
}

func (_u *TicketUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ticket.Table, ticket.Columns, sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(ticket.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ticket.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(ticket.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(ticket.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(ticket.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ClosedBy(); ok {
		_spec.SetField(ticket.FieldClosedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedClosedBy(); ok {
		_spec.AddField(ticket.FieldClosedBy, field.TypeInt64, value)
	}
	if _u.mutation.ClosedByCleared() {
		_spec.ClearField(ticket.FieldClosedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(ticket.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(ticket.FieldClosedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastReplyAt(); ok {
		_spec.SetField(ticket.FieldLastReplyAt, field.TypeTime, value)
	}
	if _u.mutation.LastReplyAtCleared() {
		_spec.ClearField(ticket.FieldLastReplyAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ticket.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticket.UserTable,
			Columns: []string{ticket.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticket.UserTable,
			Columns: []string{ticket.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticket.MessagesTable,
			Columns: []string{ticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticket.MessagesTable,
			Columns: []string{ticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticket.MessagesTable,
			Columns: []string{ticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TicketUpdateOne is the builder for updating a single Ticket entity.
type TicketUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TicketMutation
}

// SetUserID sets the "user_id" field.
func (_u *TicketUpdateOne) SetUserID(v int64) *TicketUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableUserID(v *int64) *TicketUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *TicketUpdateOne) SetTitle(v string) *TicketUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableTitle(v *string) *TicketUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TicketUpdateOne) SetStatus(v string) *TicketUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableStatus(v *string) *TicketUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TicketUpdateOne) SetCreatedBy(v int64) *TicketUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableCreatedBy(v *int64) *TicketUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *TicketUpdateOne) AddCreatedBy(v int64) *TicketUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *TicketUpdateOne) ClearCreatedBy() *TicketUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetClosedBy sets the "closed_by" field.
func (_u *TicketUpdateOne) SetClosedBy(v int64) *TicketUpdateOne {
	_u.mutation.ResetClosedBy()
	_u.mutation.SetClosedBy(v)
	return _u
}

// SetNillableClosedBy sets the "closed_by" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableClosedBy(v *int64) *TicketUpdateOne {
	if v != nil {
		_u.SetClosedBy(*v)
	}
	return _u
}

// AddClosedBy adds value to the "closed_by" field.
func (_u *TicketUpdateOne) AddClosedBy(v int64) *TicketUpdateOne {
	_u.mutation.AddClosedBy(v)
	return _u
}

// ClearClosedBy clears the value of the "closed_by" field.
func (_u *TicketUpdateOne) ClearClosedBy() *TicketUpdateOne {
	_u.mutation.ClearClosedBy()
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *TicketUpdateOne) SetClosedAt(v time.Time) *TicketUpdateOne {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableClosedAt(v *time.Time) *TicketUpdateOne {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *TicketUpdateOne) ClearClosedAt() *TicketUpdateOne {
	_u.mutation.ClearClosedAt()
	return _u
}

// SetLastReplyAt sets the "last_reply_at" field.
func (_u *TicketUpdateOne) SetLastReplyAt(v time.Time) *TicketUpdateOne {
	_u.mutation.SetLastReplyAt(v)
	return _u
}

// SetNillableLastReplyAt sets the "last_reply_at" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableLastReplyAt(v *time.Time) *TicketUpdateOne {
	if v != nil {
		_u.SetLastReplyAt(*v)
	}
	return _u
}

// ClearLastReplyAt clears the value of the "last_reply_at" field.
func (_u *TicketUpdateOne) ClearLastReplyAt() *TicketUpdateOne {
	_u.mutation.ClearLastReplyAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TicketUpdateOne) SetUpdatedAt(v time.Time) *TicketUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *TicketUpdateOne) SetUser(v *User) *TicketUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the TicketMessage entity by IDs.
func (_u *TicketUpdateOne) AddMessageIDs(ids ...int64) *TicketUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the TicketMessage entity.
func (_u *TicketUpdateOne) AddMessages(v ...*TicketMessage) *TicketUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the TicketMutation object of the builder.
func (_u *TicketUpdateOne) Mutation() *TicketMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TicketUpdateOne) ClearUser() *TicketUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearMessages clears all "messages" edges to the TicketMessage entity.
func (_u *TicketUpdateOne) ClearMessages() *TicketUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to TicketMessage entities by IDs.
func (_u *TicketUpdateOne) RemoveMessageIDs(ids ...int64) *TicketUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to TicketMessage entities.
func (_u *TicketUpdateOne) RemoveMessages(v ...*TicketMessage) *TicketUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the TicketUpdate builder.
func (_u *TicketUpdateOne) Where(ps ...predicate.Ticket) *TicketUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TicketUpdateOne) Select(field string, fields ...string) *TicketUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Ticket entity.
func (_u *TicketUpdateOne) Save(ctx context.Context) (*Ticket, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TicketUpdateOne) SaveX(ctx context.Context) *Ticket {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TicketUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TicketUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TicketUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ticket.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TicketUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := ticket.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Ticket.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := ticket.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Ticket.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Ticket.user"`)
	}
	return nil
}

func (_u *TicketUpdateOne) sqlSave(ctx context.Context) (_node *Ticket, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ticket.Table, ticket.Columns, sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Ticket.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ticket.FieldID)
		for _, f := range fields {
			if !ticket.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ticket.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(ticket.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ticket.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(ticket.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(ticket.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(ticket.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ClosedBy(); ok {
		_spec.SetField(ticket.FieldClosedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedClosedBy(); ok {
		_spec.AddField(ticket.FieldClosedBy, field.TypeInt64, value)
	}
	if _u.mutation.ClosedByCleared() {
		_spec.ClearField(ticket.FieldClosedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(ticket.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(ticket.FieldClosedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastReplyAt(); ok {
		_spec.SetField(ticket.FieldLastReplyAt, field.TypeTime, value)
	}
	if _u.mutation.LastReplyAtCleared() {
		_spec.ClearField(ticket.FieldLastReplyAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ticket.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticket.UserTable,
			Columns: []string{ticket.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticket.UserTable,
			Columns: []string{ticket.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticket.MessagesTable,
			Columns: []string{ticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticket.MessagesTable,
			Columns: []string{ticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticket.MessagesTable,
			Columns: []string{ticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Ticket{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
